#!/usr/bin/env node
/**
 * C-381 Docs Guard — witness checks for handbook canon/archive hygiene.
 *
 * Checks (default warn-only except --strict):
 *   1. Nav/reality — every mkdocs nav .md exists; orphans under docs/ flagged
 *   2. Staleness — front-matter last_witnessed_cycle > 20 cycles behind current
 *   3. Index proliferation — hand-maintained *INDEX* files outside allowlist
 *   4. Journal nav — mkdocs Cycle Journal matches filesystem journal files
 *
 * Usage:
 *   node scripts/docs-guard.mjs [--strict] [--json]
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  cycleNumber,
  listJournalFiles,
  listMarkdownFiles,
  parseFrontMatter,
  parseMkdocsNav,
  readMkdocs,
} from './lib/docs-nav.mjs';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = path.join(ROOT, 'docs');
const JOURNALS = path.join(DOCS, 'journals');
const STRICT = process.argv.includes('--strict');
const JSON_OUT = process.argv.includes('--json');

const STALE_CYCLE_THRESHOLD = 20;
const ORPHAN_EXCLUDE = ['10-ARCHIVES', '09-APPENDICES/assets'];
const INDEX_ALLOWLIST = new Set([
  'INDEX.md',
  'journals/archive.md',
  '08-REFERENCE/INDEX.md',
  '02-THEORETICAL-FOUNDATIONS/cathedrals/INDEX.md',
]);
const INDEX_PATTERN = /(?:MASTER_INDEX|SUBJECT_INDEX|FOLDER_INDEX|NAVIGATION_GUIDE|DOCUMENT_REGISTRY|ACADEMIC_INDEX|LATEX_INDEX)/i;

const errors = [];
const warnings = [];

function fail(msg) {
  errors.push(msg);
}

function warn(msg) {
  warnings.push(msg);
}

const cycle = JSON.parse(fs.readFileSync(path.join(ROOT, 'cycle.json'), 'utf8'));
const currentCycle = cycle.current_cycle;
const currentNum = cycleNumber(currentCycle);
const mkdocs = readMkdocs(ROOT);
const navEntries = parseMkdocsNav(mkdocs);
const navPaths = new Set(navEntries.map((e) => e.path));

// 1. Nav/reality
for (const entry of navEntries) {
  const full = path.join(DOCS, entry.path);
  if (!fs.existsSync(full)) {
    fail(`Nav link missing file: "${entry.title}" → ${entry.path}`);
  }
}

const allDocs = listMarkdownFiles(DOCS, ORPHAN_EXCLUDE);
const orphans = allDocs.filter((rel) => !navPaths.has(rel));
if (orphans.length > 0) {
  const sample = orphans.slice(0, 15);
  warn(
    `${orphans.length} markdown file(s) under docs/ not reachable from mkdocs nav ` +
      `(showing ${sample.length}): ${sample.join(', ')}${orphans.length > 15 ? '…' : ''}`
  );
}

// 2. Staleness (canon docs with front-matter only)
for (const rel of navPaths) {
  const full = path.join(DOCS, rel);
  if (!fs.existsSync(full)) continue;
  const meta = parseFrontMatter(full);
  if (!meta?.last_witnessed_cycle) continue;
  if (meta.status === 'archived') continue;
  const witnessed = cycleNumber(meta.last_witnessed_cycle);
  if (currentNum - witnessed > STALE_CYCLE_THRESHOLD) {
    warn(
      `Stale witness: ${rel} last_witnessed_cycle=${meta.last_witnessed_cycle} ` +
        `(>${STALE_CYCLE_THRESHOLD} cycles behind ${currentCycle})`
    );
  }
}

// 3. Index proliferation
for (const rel of allDocs) {
  const base = path.basename(rel);
  if (INDEX_ALLOWLIST.has(rel) || INDEX_ALLOWLIST.has(base)) continue;
  if (INDEX_PATTERN.test(rel)) {
    const level = STRICT ? fail : warn;
    level(`Hand-maintained index surface: ${rel} (collapse to generated docs/INDEX.md)`);
  }
}
const docIndexJson = path.join(DOCS, 'document-index.json');
if (fs.existsSync(docIndexJson)) {
  const level = STRICT ? fail : warn;
  level('Hand-maintained docs/document-index.json — should be generated or archived');
}

// 4. Journal nav drift
const journalFiles = listJournalFiles(JOURNALS);
const journalNav = navEntries
  .filter((e) => e.path.startsWith('journals/C-') && e.path !== 'journals/archive.md')
  .map((e) => e.path.replace('journals/', '').replace('.md', ''));

const expectedTop = journalFiles.slice(0, 10).map((j) => j.cycle);
const missingFromNav = expectedTop.filter((c) => !journalNav.includes(c));
const staleInNav = journalNav.filter((c) => !expectedTop.includes(c));

if (missingFromNav.length > 0) {
  warn(`Journal nav missing recent cycles: ${missingFromNav.join(', ')} (run npm run docs:sync-journal-nav)`);
}
if (staleInNav.length > 0 && journalFiles.length > 0) {
  const newestNav = Math.max(...journalNav.map(cycleNumber));
  const newestFile = journalFiles[0]?.num ?? 0;
  if (newestFile > newestNav) {
    warn(`Journal nav lags filesystem: newest nav ${newestNav}, newest file C-${newestFile}`);
  }
}

// Stale INDEX.md cycle reference
const indexPath = path.join(DOCS, 'INDEX.md');
if (fs.existsSync(indexPath)) {
  const index = fs.readFileSync(indexPath, 'utf8');
  if (!index.includes('GENERATED by scripts/generate-handbook-index.mjs')) {
    warn('docs/INDEX.md is not generated — run npm run docs:generate-index');
  }
  const indexCycle = index.match(/\*\*Cycle:\*\*\s*(C-\d+)/)?.[1];
  if (indexCycle && indexCycle !== currentCycle) {
    warn(`docs/INDEX.md cycle (${indexCycle}) != cycle.json (${currentCycle})`);
  }
}

const result = {
  ok: errors.length === 0,
  strict: STRICT,
  current_cycle: currentCycle,
  nav_entries: navEntries.length,
  orphan_count: orphans.length,
  errors,
  warnings,
};

if (JSON_OUT) {
  console.log(JSON.stringify(result, null, 2));
} else {
  if (warnings.length) {
    console.log('⚠️  Docs Guard warnings:');
    for (const w of warnings) console.log(`  - ${w}`);
  }
  if (errors.length) {
    console.error('❌ Docs Guard errors:');
    for (const e of errors) console.error(`  - ${e}`);
  }
  if (!errors.length && !warnings.length) {
    console.log(`✅ Docs Guard passed at ${currentCycle}.`);
  } else if (!errors.length) {
    console.log(`✅ Docs Guard passed with ${warnings.length} warning(s) at ${currentCycle}.`);
  }
}

process.exit(errors.length > 0 ? 1 : 0);
